# Generated by Django 5.1.2 on 2024-10-19 06:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_name', models.CharField(max_length=100)),
                ('ac_no', models.CharField(max_length=20, unique=True)),
                ('ac_mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('account_type', models.CharField(choices=[('Saving', 'Saving'), ('Current', 'Current'), ('OV', 'Overdraft')], max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_from', models.IntegerField(default=0, editable=False)),
                ('amount_to', models.IntegerField(default=0, editable=False)),
                ('from_status', models.CharField(default='debited', editable=False, max_length=20)),
                ('to_status', models.CharField(default='credited', editable=False, max_length=20)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_from', to='accounts.account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_to', to='accounts.account')),
            ],
        ),
    ]
