# Generated by Django 5.1.2 on 2025-01-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ac_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount_from',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount_to',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='from_status',
            field=models.CharField(default='Debited', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to_status',
            field=models.CharField(default='Credited', editable=False, max_length=20),
        ),
    ]
