# Generated by Django 5.1.2 on 2025-01-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_ac_name_alter_transfer_amount_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ac_no',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
