# Generated by Django 5.1.2 on 2025-01-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_ac_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ac_mobile',
            field=models.CharField(max_length=10),
        ),
    ]
